version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: swift_trainer_redis
    ports:
      - "6380:6379"
    volumes:
      - ./volumes/redis/data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  swift_trainer_api:
    image: swift_trainer_api:latest
    container_name: swift_trainer_api
    environment:
      - ENVIRONMENT=dev
      - PYTHONPATH=/swift-api
      - NCCL_IB_DISABLE=1
      - NCCL_P2P_DISABLE=1
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    network_mode: host
    ipc: host
    volumes:
      - /home/sunjinf/github_projet/swift-api:/swift-api
      - /data/nfs/swift-api-data:/app_data
    working_dir: /swift-api
    entrypoint: ["python", "start.py"]