version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: swift_trainer_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  swift_trainer_api:
    build: .
    container_name: swift_trainer_api
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output
      - ./data:/app/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - LOG_LEVEL=INFO
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: 